# If you intended to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 172.31.18.17
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: controlplane
  user: ubuntu
  docker_socket: /var/run/docker.sock
  ssh_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAyU2kzXaRthsalB6vgQsgpJXURpKPG3pEQei55XuFH6871JoC
    v9p68OxiUuKelkCTfBkXMCuNe0QUJpJLlLsofET+USpl5oTyLR2uFix9BpsOtBps
    EzNnEcTyrodaEOiATMZQnA8kWNcPnhegv6dx0a/9+a4Q9tNXeATTpwAcaEZxgo7f
    vQfuUXRrGVCxFe1d0fJakM04RwE3s1Fu4kTuAHfq1kFs81Eh9h564KDqrgoonlhg
    /n+w3QCtxcDaRsdMQ77DoOMKcMmsjUT1gOYxhPmnd6pKTXPhJK0cz6EaBXeqmQoO
    Wkpeyw1i+C3YHCMjFD6AcODSQ6gF1kJIgituqQIDAQABAoIBAFGfHtyEYA6TrNI0
    IvtS1LiHW9wFnusIR1bmE0IeNFslhT/t9oFuB/1aC4AKDT1lD6f40HMipao+b2E4
    Xlb/ECpbGzcz1r+CVmO+rhCll0gvZOXX9MxQQlFtJu1nSjii3SrEGnk8loNDKDz0
    3aP4M+lOz88GKjC6frPWWS9UlzAb758QBPYEeNIWGRVwXko3fjvhY3ZFQhmj3gN1
    Stins3Ca4vb0sZgJOUxiVzDr9EuGlas7pSNWkSavev3wXWwYGC+yUv265yQ3Syy/
    aSY6tNtlMbEH2PyZxuF6rYhTa86oATth/kqxIHlyD7zkFFO17U4Msw3gWQbKZACw
    OI9AqcUCgYEA71KMkqdoaPGUH8GHbhagPagoRxJhDGs7ODfU9oOmTLhQpziN6wMN
    HhpwgdspbXIyMvA3IBkO1Po/FJHXmgqSwM3PU+lXMcKcJI7iT2Ory1yB/mSdu6rD
    AiWmP+jBwzyz0eLOrA8qxC26xHfk6EWrFqYkld2PbsEnfNFj2QobbUcCgYEA11TX
    ta2/NU/bGZudGlFMBeXV/WqW045Chz+5fO1KobPqEvnt4iKQ0ovY8ZnMLZ125Zpj
    G1p00FAm668Evg7uTT9TZm3vZOPfaBr0I94+VC4rj9nRoHajPAwG8Jpe3GA9W/Wj
    xQ2PJw+OPb+5uk328gEzRYXibVW/t0eq8yY9fI8CgYB0I59MXClzJCk57/UFG73P
    rhc9xlGKcU9fzNhweRrvCFM7k1prviNThIksu2qzTkPGLITT8tUbzgVmug/jFVZ6
    cmY21noWD9cudpik5j2shswe5D0XoZrZI+Q2B4JgeMjbBjI9lW6vnXGRfo17mrOY
    XjBK+iZtHRdIn2TRIvKEaQKBgCoQFrsUn59IZCJSdZPogZM9XFnOcnwM9A37cr5m
    lAeWX4kpbUCZQ/T9AHnhczMN6WXcjLORLfRrU88CN0jxHbfVQPNnUjZBFSj+6uX+
    yeojwrqs7/gKdMSMDOb/ILynyBSonT8m8OnObhi91QgBptWLSnqwNpTpBTRGOayZ
    sbUdAoGAEZtADiXmw5BuigkvMBRC+/W6LMT1p+pn+AJCr8ZMMhH9eDwKI00lE++K
    Hen5Cz+07PoTaIj4W/V9jH9zhZUOVtyGU/vs4q94gDU0kYw1hPjmDlvnlpvNHdC+
    Kqr2yvYofls9o0taSDtTWN7xFNsLqHRrFA4nRqQ8cHRsT5lKQC8=
    -----END RSA PRIVATE KEY-----
  ssh_key_path: ~/.ssh/id_ed25519
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 172.31.21.169
  port: "22"
  internal_address: ""
  role:
  - worker
  - etcd
  hostname_override: worker-1
  user: ubuntu
  docker_socket: /var/run/docker.sock
  ssh_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAyU2kzXaRthsalB6vgQsgpJXURpKPG3pEQei55XuFH6871JoC
    v9p68OxiUuKelkCTfBkXMCuNe0QUJpJLlLsofET+USpl5oTyLR2uFix9BpsOtBps
    EzNnEcTyrodaEOiATMZQnA8kWNcPnhegv6dx0a/9+a4Q9tNXeATTpwAcaEZxgo7f
    vQfuUXRrGVCxFe1d0fJakM04RwE3s1Fu4kTuAHfq1kFs81Eh9h564KDqrgoonlhg
    /n+w3QCtxcDaRsdMQ77DoOMKcMmsjUT1gOYxhPmnd6pKTXPhJK0cz6EaBXeqmQoO
    Wkpeyw1i+C3YHCMjFD6AcODSQ6gF1kJIgituqQIDAQABAoIBAFGfHtyEYA6TrNI0
    IvtS1LiHW9wFnusIR1bmE0IeNFslhT/t9oFuB/1aC4AKDT1lD6f40HMipao+b2E4
    Xlb/ECpbGzcz1r+CVmO+rhCll0gvZOXX9MxQQlFtJu1nSjii3SrEGnk8loNDKDz0
    3aP4M+lOz88GKjC6frPWWS9UlzAb758QBPYEeNIWGRVwXko3fjvhY3ZFQhmj3gN1
    Stins3Ca4vb0sZgJOUxiVzDr9EuGlas7pSNWkSavev3wXWwYGC+yUv265yQ3Syy/
    aSY6tNtlMbEH2PyZxuF6rYhTa86oATth/kqxIHlyD7zkFFO17U4Msw3gWQbKZACw
    OI9AqcUCgYEA71KMkqdoaPGUH8GHbhagPagoRxJhDGs7ODfU9oOmTLhQpziN6wMN
    HhpwgdspbXIyMvA3IBkO1Po/FJHXmgqSwM3PU+lXMcKcJI7iT2Ory1yB/mSdu6rD
    AiWmP+jBwzyz0eLOrA8qxC26xHfk6EWrFqYkld2PbsEnfNFj2QobbUcCgYEA11TX
    ta2/NU/bGZudGlFMBeXV/WqW045Chz+5fO1KobPqEvnt4iKQ0ovY8ZnMLZ125Zpj
    G1p00FAm668Evg7uTT9TZm3vZOPfaBr0I94+VC4rj9nRoHajPAwG8Jpe3GA9W/Wj
    xQ2PJw+OPb+5uk328gEzRYXibVW/t0eq8yY9fI8CgYB0I59MXClzJCk57/UFG73P
    rhc9xlGKcU9fzNhweRrvCFM7k1prviNThIksu2qzTkPGLITT8tUbzgVmug/jFVZ6
    cmY21noWD9cudpik5j2shswe5D0XoZrZI+Q2B4JgeMjbBjI9lW6vnXGRfo17mrOY
    XjBK+iZtHRdIn2TRIvKEaQKBgCoQFrsUn59IZCJSdZPogZM9XFnOcnwM9A37cr5m
    lAeWX4kpbUCZQ/T9AHnhczMN6WXcjLORLfRrU88CN0jxHbfVQPNnUjZBFSj+6uX+
    yeojwrqs7/gKdMSMDOb/ILynyBSonT8m8OnObhi91QgBptWLSnqwNpTpBTRGOayZ
    sbUdAoGAEZtADiXmw5BuigkvMBRC+/W6LMT1p+pn+AJCr8ZMMhH9eDwKI00lE++K
    Hen5Cz+07PoTaIj4W/V9jH9zhZUOVtyGU/vs4q94gDU0kYw1hPjmDlvnlpvNHdC+
    Kqr2yvYofls9o0taSDtTWN7xFNsLqHRrFA4nRqQ8cHRsT5lKQC8=
    -----END RSA PRIVATE KEY-----
  ssh_key_path: ~/.ssh/id_ed25519
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: null
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_configuration: ""
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_args_array: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_args_array: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: canal
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []
  enable_br_netfilter: null
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: rancher/mirrored-coreos-etcd:v3.5.16
  alpine: rancher/rke-tools:v0.1.114
  nginx_proxy: rancher/rke-tools:v0.1.114
  cert_downloader: rancher/rke-tools:v0.1.114
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.114
  kubedns: rancher/mirrored-k8s-dns-kube-dns:1.23.0
  dnsmasq: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.23.0
  kubedns_sidecar: rancher/mirrored-k8s-dns-sidecar:1.23.0
  kubedns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:v1.9.0
  coredns: rancher/mirrored-coredns-coredns:1.11.3
  coredns_autoscaler: rancher/mirrored-cluster-proportional-autoscaler:v1.9.0
  nodelocal: rancher/mirrored-k8s-dns-node-cache:1.23.0
  kubernetes: rancher/hyperkube:v1.27.14-rancher1
  flannel: rancher/mirrored-flannel-flannel:v0.27.3
  flannel_cni: rancher/flannel-cni:v1.4.1-rancher1
  calico_node: rancher/mirrored-calico-node:v3.30.2
  calico_cni: rancher/calico-cni:v3.30.2-rancher1
  calico_controllers: rancher/mirrored-calico-kube-controllers:v3.30.2
  calico_ctl: rancher/mirrored-calico-ctl:v3.30.2
  calico_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.30.2
  canal_node: rancher/mirrored-calico-node:v3.30.2
  canal_cni: rancher/calico-cni:v3.30.2-rancher1
  canal_controllers: rancher/mirrored-calico-kube-controllers:v3.30.2
  canal_flannel: rancher/mirrored-flannel-flannel:v0.27.3
  canal_flexvol: rancher/mirrored-calico-pod2daemon-flexvol:v3.30.2
  weave_node: ""
  weave_cni: ""
  pod_infra_container: rancher/mirrored-pause:3.7
  ingress: rancher/nginx-ingress-controller:nginx-1.12.1-rancher4
  ingress_backend: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher2
  ingress_webhook: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.5.2
  metrics_server: rancher/mirrored-metrics-server:v0.7.2
  windows_pod_infra_container: rancher/mirrored-pause:3.7
  aci_cni_deploy_container: noiro/cnideploy:6.1.1.4.81c2369
  aci_host_container: noiro/aci-containers-host:6.1.1.4.81c2369
  aci_opflex_container: noiro/opflex:6.1.1.4.81c2369
  aci_mcast_container: noiro/opflex:6.1.1.4.81c2369
  aci_ovs_container: noiro/openvswitch:6.1.1.4.81c2369
  aci_controller_container: noiro/aci-containers-controller:6.1.1.4.81c2369
  aci_gbp_server_container: ""
  aci_opflex_server_container: ""
ssh_key_path: ~/.ssh/id_ed25519
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: null
enable_cri_dockerd: null
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
  tolerations: []
  default_backend: null
  default_http_backend_priority_class_name: ""
  nginx_ingress_controller_priority_class_name: ""
  default_ingress_class: null
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  ignore_proxy_env_vars: false
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
  metrics_server_priority_class_name: ""
restore:
  restore: false
  snapshot_name: ""
rotate_encryption_key: false
dns: null
cri_dockerd_stream_server_address: ""
cri_dockerd_stream_server_port: ""